development:
  adapter: postgresql
  encoding: unicode
  database: dashboard_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dashboard_test
  pool: 5
  username: root
  password:
